### ISSUE TITLE
Using React Router for web+native

### ISSUE THREAD

**Issue by dohomi** [onejs/one#15]
Hey Guys,

would it not be a good idea to use React Router for web and native, as that might reduce overhead? I just don't know how nicely the Stack would run on expo but I assume it should work? 

It would make it easy to have a 
router.tsx => importing react-router-native
router.web.tsx => importing react-router-dom

**Comment by dohomi** [comment]
thanks for the heads up, I search for an integration with React Native + Vite + React Router

**Comment by redbar0n** [comment]
See also: https://github.com/oedotme/generouted

**Comment by natew** [comment]
Right now theres the expo-router example, something broke when I extracted it out into this new repo but i think its just a single bug away from running. It uses import.meta.glob.

Seems like you could probably replace it with many routers. I went with Expo since they have a working native example built on top of react-native navigation which is in itself a router and probably the only good one that works with RN.

Would be a huge help if anyone wants to try getting expo-router example running. I'll try and find time but it may be a bit.

**Comment by redbar0n** [comment]
FWIW, seems like [this line](https://github.com/natew/vxrn/blob/7cdeaf48c4d41fb84be2827a88e5524f3a57e697/examples/expo-router/src/App.tsx#L6):

```tsx
const modules = import.meta.glob('../app/**/*.tsx')
```

should be:
```tsx
const modules = import.meta.glob('../app/*.tsx')
```

since the tsx files are stored directly under the app folder.

**Comment by natew** [comment]
Thanks @redbar0n 

@dohomi Thanks. I've already got it working actually using many of the same settings form that gist in this repo. See examples/expo-router.  Just needs some cleanup.

**Comment by TheUltDev** [comment]
@dohomi yes, I use a custom React Router for this reason, it's actually quite easy:
https://github.com/kat-tax/exo/tree/master/library/src/layout/navigation

For advanced apps I'm looking into generating a react-native-router config for native, and either React Router, Wouter, or similar for web based on a single config. (I'm not a fan of file based routing as text is more flexible and I don't like the directory structure to be limited and coupled to routing.)
