### ISSUE TITLE
Add platform-specific extension for server side code.

### ISSUE THREAD

**Issue by clayrisser** [onejs/one#151]
It would be nice if there was a platform-specific extensions for server side code, for example `file.server.ts`. This could be useful in certain situations where a module is used but you don't want it all bundled in the browser.

**Comment by natew** [comment]
This one doesn't make sense because unlike platform extensions which are always going to be separated and consistently separated, server and client "share" code, so on client if you didn't have that path you'd have runtime errors.

You can do the usual `typeof window` and we should export probably some constants that make this easier (and that we can optimize).

We also have some plans for `serverLoader` where your loader data is never passed to the client, as well as a `<ServerOnly>` component that you can then pass that server loaded data to. This is something we're building now since it helps us optimize markdown pages much like you would with RSC, only with very minimal implementation cost and easy to use. That should land here soon.

**Comment by clayrisser** [comment]
Ok, that works. I can use other approaches to handle it. If I have some code on the server I don't want bundled I can do an `await import()` inside of an if statement.
